### ISSUE TITLE
Planet repositioning is visible

### ISSUE THREAD

**Issue by mikepmerritt** [mattcmerritt/Planetary-Protector#3]
As the code is right now, the lower priority (last generated) planet will reposition if two planets are colliding. However, despite implementing two different algorithms for picking a new location for the planet, it still takes a lot of passes with either algorithm to get a valid location as the planet's priority number increases. For reference, the tenth planet placed usually has to take between 15 and 25 passes at repositioning just to find a spot. With so many passes occurring, there is a brief window where the planets can be seen moving, which is likely not what we want. Presumably, if we increase the size or number of planets later on, this problem will only get much worse, so we should focus on resolving it now.

There are several different ways we can fix this issue, but none are perfect:
- implement a loading screen for a second while the planets sort themselves out (might be hard to interact with loading screen due to no key presses)
- set predetermined positions for the planets instead of random ones (variety suffers, but startup performance is much better and reposition algorithms are unnecessary)
-  make something in the Planet Spawner that reads the positions of all planets and finds a gap to place the new planet (like what we have now, this would scale poorly and might still run slow)

**Comment by mattcmerritt** [comment]
I think that it would be pretty easy to implement a loading screen, as we can just put up an UI canvas on top of the game and have a progress bar that shows the amount of planets currently loaded. Once the level is loaded, the canvas would fade out to show the loaded level. We could also use some flags in order to prevent the game from playing while loading.

As for the planet positions, we probably will end up doing set placements if we choose to do levels, but I want to try to had random placement for an endless mode.

**Comment by mikepmerritt** [comment]
Ok, so we'll use the loading screen approach then. That works out, because then we can increase the number of passes if planets aren't spawning.
